DROP TABLE IF EXISTS Stock;
CREATE TABLE Stock (
  ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
  INGREDIENT VARCHAR2(100) NOT NULL,
  QUANTITY   BIGINT        NOT NULL
);

INSERT INTO Stock (INGREDIENT, QUANTITY) VALUES ('Farine', 50000);
INSERT INTO Stock (INGREDIENT, QUANTITY) VALUES ('Sucre', 50000);
INSERT INTO Stock (INGREDIENT, QUANTITY) VALUES ('Oeuf', 50000);
INSERT INTO Stock (INGREDIENT, QUANTITY) VALUES ('Lait', 50000);
INSERT INTO Stock (INGREDIENT, QUANTITY) VALUES ('BeurreFondu', 50000);
INSERT INTO Stock (INGREDIENT, QUANTITY) VALUES ('ChocolatFondu', 50000);
INSERT INTO Stock (INGREDIENT, QUANTITY) VALUES ('CremeFraiche', 50000);
INSERT INTO Stock (INGREDIENT, QUANTITY) VALUES ('PepitesDeChocolat', 50000);
